---
name: actionlint
env:
  KHULNASOFT_LOG_COLOR: always
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.10.2-1
          policy_allow: "true"
      - run: actionlint -ignore "duplicate value"
