---
name: test
on:
  pull_request:
    branches: [main]
permissions: {}
env:
  KHULNASOFT_LOG_COLOR: always
jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      check-files: ${{steps.changes.outputs.check-files}}
      generate-registry: ${{steps.changes.outputs.generate-registry}}
      json-schema: ${{steps.changes.outputs.json-schema}}
      test-earthly: ${{steps.changes.outputs.test-earthly}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@v2.11.1 # v2.11.1
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json5
            check-files:
              - pkgs/**/pkg.yaml
              - pkgs/**/registry.yaml
            generate-registry:
              - khulnasoft/generate-registry.yaml
              - registry.yaml
              - pkgs/**/registry.yaml
            json-schema:
              - registry.yaml
            test-earthly:
              - Earthfile
              - khulnasoft/earthly.yaml
              - khulnasoft/earthly-test.yaml

  status-check:
    # This job is used for main branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    runs-on: ubuntu-latest
    needs:
      - enable-automerge-renovate
      - renovate-config-validator
      - check-files
      - generate-registry
      - json-schema
      - prettier
      - test-earthly
      - test
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  enable-automerge-renovate:
    runs-on: ubuntu-latest
    environment: renovate
    if: |
      github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0 # v1.8.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - name: Enable auto-merge
        run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --auto --delete-branch "$PR_NUMBER"
        env:
          # github.token is unavailable, because github.token doesn't have a permission to delete a branch `renovate/*`
          # pull-requests: write and contents: write are required
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          PR_NUMBER: ${{github.event.pull_request.number}}

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: sulaiman-coder/renovate-config-validator-workflow/.github/workflows/validate.yaml@v0.2.2 # v0.2.2
    needs: path-filter
    if: ${{needs.path-filter.outputs.renovate-config-validator == 'true'}}
    permissions:
      contents: read

  check-files:
    runs-on: ubuntu-latest
    needs: path-filter
    if: ${{needs.path-filter.outputs.check-files == 'true'}}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: khulnasoftproj/registry-action/check-files@v0.2.0 # v0.2.0

  generate-registry:
    runs-on: ubuntu-latest
    needs: path-filter
    if: ${{needs.path-filter.outputs.generate-registry == 'true'}}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.10.2-1
          policy_allow: "true"
      - uses: khulnasoftproj/registry-action/generate-registry@v0.2.0 # v0.2.0

  json-schema:
    runs-on: ubuntu-latest
    needs: path-filter
    if: ${{needs.path-filter.outputs.json-schema == 'true'}}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: khulnasoftproj/registry-action/validate-json-schema@v0.2.0 # v0.2.0

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - run: npm i -g prettier
      - run: prettier -c .

  test-earthly:
    runs-on: ubuntu-latest
    needs: path-filter
    if: ${{needs.path-filter.outputs.test-earthly == 'true'}}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.10.2-1
          policy_allow: "true"
        env:
          KHULNASOFT_GITHUB_TOKEN: ${{github.token}}
      - run: earthly +test --pkg=google/wire

  ci-info:
    runs-on: ubuntu-latest
    env:
      KHULNASOFT_CONFIG: khulnasoft/ci-info.yaml
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.10.2-1
          policy_allow: "true"
        env:
          KHULNASOFT_GITHUB_TOKEN: ${{github.token}}
      - uses: sulaiman-coder/ci-info-action/store@v0.1.2 # v0.1.2
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: echo "https://github.com/khulnasoftproj/khulnasoft-registry/pull/$CI_INFO_PR_NUMBER" >> "$GITHUB_STEP_SUMMARY"

  test:
    needs: ci-info
    strategy:
      matrix:
        env:
          - runs-on: windows-latest
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
          - runs-on: ubuntu-latest
            goarch: arm64
          - runs-on: macos-latest
            goos: darwin
            goarch: arm64
          - runs-on: windows-latest
            goarch: arm64
    runs-on: ${{ matrix.env.runs-on }}
    defaults:
      run:
        shell: bash
    env:
      KHULNASOFT_CONFIG: khulnasoft/test.yaml
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: sulaiman-coder/ci-info-action/restore@v0.1.2 # v0.1.2

      # - name: Generate token
      #   id: generate_token
      #   uses: tibdex/github-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.10.2-1
          policy_allow: "true"
        env:
          KHULNASOFT_GITHUB_TOKEN: ${{github.token}}

      - uses: khulnasoftproj/registry-action/test@v0.2.0 # v0.2.0
        with:
          goos: ${{ matrix.env.goos }}
          goarch: ${{ matrix.env.goarch }}
          go_version: "1.20.3"
        env:
          GITHUB_TOKEN: ${{github.token}}
