---
name: Update packages by khulnasoft-registry-updater
on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/10 * * * *"

env:
  KHULNASOFT_GLOBAL_CONFIG: ${{ github.workspace }}/khulnasoft-all.yaml
  KHULNASOFT_LOG_COLOR: always

jobs:
  update-pkgs:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: khulnasoftproj/khulnasoft-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          khulnasoft_version: v2.10.2-1
          policy_allow: "true"
          khulnasoft_opts: -l -a
        env:
          KHULNASOFT_GITHUB_TOKEN: ${{github.token}}
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - run: khulnasoft-registry-updater
        env:
          KHULNASOFT_REGISTRY_UPDATER_CONTAINER_REGISTRY_TOKEN: ${{github.token}}
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
