packages:
  - type: github_release
    repo_owner: grafana
    repo_name: grafana-kiosk
    description: Kiosk Utility for Grafana
    rosetta2: true
    format: raw
    asset: grafana-kiosk.{{.OS}}.{{.Arch}}
    supported_envs:
      - darwin
      - linux
      - amd64
